# Website settings
title: Praveen Palanisamy
description: Building Autonomous Systems, AI, Deep RL Agents & Robots
keywords: Praveen,Praveen Palanisamy, HOIAWOG
# url: https://praveen-palanisamy.github.io
uri: "https://praveenp.com"
# url: http://127.0.0.1:4000
baseurl: ""
img_path: /static/assets/img/blog # url should be '/homepage/static/assets/img/blog' as before
permalink: /:categories/:title/
# author -- index page "about me" section
author:
  name: Praveen Palanisamy # used as blog posts' author.
  first_name: Praveen # Used at index page about me section.
  last_name: Palanisamy # Used at index page about me section.
  avatar: /static/assets/img/avatar.jpg
  links: # Custom links.
    - label: "Patents"
      icon: "fa fa-2x fa-trophy"
      url: "https://link.lens.org/NsO8YdGEyxc"
    - label: "Google Scholar"
      icon: "fa fa-2x fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=gHmYX8YAAAAJ"
  github_username: praveen-palanisamy
  google_scholar_uid: gHmYX8YAAAAJ
  linkedin_id: praveenpalanisamy
  twitter_username: praveenpsamy
  email: email@praveenp.com
  stackoverflow: 1310924
  cv:
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: fa-angle-left
    - name: fa-helicopter
  skill_icon2:
    # - name: icon-azure
    - name: fa-angle-double-down
  desc: Praveen Palanisamy is a Lead Principal AI Engineer and Manager at Microsoft and works on building AI/ML-powered platform products for Autonomous Systems. His current focus is on building enterprise-grade Generative AI platform capabilities including a suite of custom applications that leverage Microsoft Copilot stack, Azure OpenAI, and OSS LLMs. Recently, he has been building Copilot/Agent-based platform components, automating LLMOps pipelines, memory-agumented Agents, pretraining/finetuning custom LMMs/LLMs and prototyping full-stack AI-Apps. He leads a cross-functional team to research and engineer platform and system components that leverage and empower customers with AI capabilities such as for [Project AirSim](https://aka.ms/airsim) in the Autonomous Systems, Business AI Incubation group, building an end-to-end (Perception + Scene-Understanding + Prediction + Planning + Control) autonomy platform for autonomous aerial robots and systems using Simulation, Planet-scale Synthetics, and Deep Reinforcement learning using [Project Bonsai](https://aka.ms/bonsai). Prior to that, he was an Autonomous Driving AI Researcher at General Motors R&D in Michigan, where, he developed planning and decision making algorithms and architectures using Deep Reinforcement Learning. He is the lead inventor of [70+ patents](https://link.lens.org/NsO8YdGEyxc) in the area of autonomous systems. He has authored two practical books -- [HOIAWOG](https://praveenp.com/deeprl/hoiawog/) and [TensorFlow 2.x RL Cookbook](https://praveenp.com/deeprl/tensorflow-2.x-reinforcement-learning-cookbook/) for use by ML engineers, researchers, students and enthusiasts. He has worked at a few early-stage startups as a tech lead. He obtained his Graduate degree from the Robotics Institute, Carnegie Mellon University, and worked on Autonomous Navigation, Perception and Artificial Intelligence as a Research and Teaching Assistant.
  short_bio: Principal AI Engineering Lead,<br> Autonomous Systems,<br> Microsoft AI + Research
  location: ""

# comment
disqus:
  name: praveen-palanisamy-github

# analytics
## google analytics
ga:
  id: G-RC2T7K4L01

## google optimize
go:
  # id:

## donation
donation: off # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: off # index page carousel switch
blog_carousel: on # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Default front matter content https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: "" # All files
      type: pages
    values:
      layout: "default"
      author_profile: true
  - scope:
      path: "" # All files
      type: posts
    values:
      layout: "post"
      author_profile: true # Author profile on sidebar (left)
      toc: "true" # Table of Contents on sidebar_right
      toc_sticky: "true"
