# Website settings
title: Praveen Palanisamy
description: Building Autonomous Systems, AI, Deep RL Agents & Robots
keywords: Praveen,Praveen Palanisamy, HOIAWOG
url: https://praveen-palanisamy.github.io
# url: http://127.0.0.1:4000
baseurl: ""
img_path: /static/assets/img/blog # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:
  name: Praveen Palanisamy # used as blog posts' author.
  first_name: Praveen # Used at index page about me section.
  last_name: Palanisamy # Used at index page about me section.
  avatar: /static/assets/img/avatar.jpg
  github_username: praveen-palanisamy
  google_scholar_uid: gHmYX8YAAAAJ
  linkedin_id: praveenpalanisamy
  twitter_username: praveenpsamy
  email: email@praveenp.com
  cv:
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
  skill_icon2:
    - name: fa-linux
    - name: icon-apache
  desc: Praveen Palanisamy is a Principal AI Engineer in Autonomous Systems Business Incubation group at Microsoft, building an end-to-end (Perception + Scene-Understanding + Prediction + Planning + Control) autonomy platform for real-world autonomous robots and systems using Simulation, Deep Reinforcement Learning and Machine Teaching. Prior to that, he was an Autonomous Driving AI Researcher at General Motors R&D in Michigan, where, he developed planning and decision making algorithms and architectures using Deep Reinforcement Learning. Before that , he was at the Robotics Institute, Carnegie Mellon University, where, he worked on Autonomous Navigation, Perception and Artificial Intelligence. He holds numerous patents in the area of autonomous learning systems.

# comment
disqus:
  name: praveen-palanisamy-github

# analytics
## google analytics
ga:
  # id:

## google optimize
go:
  # id:

## donation
donation: off # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on # index page carousel switch
blog_carousel: on # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
