# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Praveen Palanisamy'
tagline:          'Autonomous driving AI research engineer'
description:      'Personal portfolio and posts on {AI, Robotics, Computer Vision, Linux-dev}'
url:              'https://praveen-palanisamy.github.io'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Praveen Palanisamy'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       ''
flickr:
github:         'https://github.com/praveen-palanisamy'
gplus:          'https://plus.google.com/+PraveenpalanisamyPraveenofpersia'
instagram:
pinterest:
linkedin:       'https://www.linkedin.com/in/praveenpalanisamy'
rss:
stackoverflow:  'https://stackoverflow.com/users/1310924/'
twitter:        'https://twitter.com/praveenpalanis5'

# Google Analytics
gahandler: ''

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'praveen-palanisamy-github'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:         1 
