# Website settings
title: Praveen Palanisamy
description: Building Autonomous Systems, AI, Deep RL Agents & Robots
keywords: Praveen,Praveen Palanisamy, HOIAWOG
url: https://praveen-palanisamy.github.io
# url: http://127.0.0.1:4000
baseurl: ""
img_path: /static/assets/img/blog # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:
  name: Praveen Palanisamy # used as blog posts' author.
  first_name: Praveen # Used at index page about me section.
  last_name: Palanisamy # Used at index page about me section.
  avatar: /static/assets/img/avatar.jpg
  github_username: praveen-palanisamy
  google_scholar_uid: gHmYX8YAAAAJ
  linkedin_id: praveenpalanisamy
  twitter_username: praveenpsamy
  email: email@praveenp.com
  cv:
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: fa-angle-left
    - name: fa-helicopter
  skill_icon2:
    # - name: icon-azure
    - name: fa-angle-double-down
  desc: Praveen Palanisamy is a Principal AI Engineer in the Autonomous Systems Business Incubation group at Microsoft, building an end-to-end (Perception + Scene-Understanding + Prediction + Planning + Control) autonomy platform for autonomous aerial robots and systems using Simulation, Deep Learning, Deep Reinforcement Learning and Machine Teaching. Prior to that, he was an Autonomous Driving AI Researcher at General Motors R&D in Michigan, where, he developed planning and decision making algorithms and architectures using Deep Reinforcement Learning. He is the lead inventor of 20+ patents in the area of learning-based autonomous mobile systems. He has worked at a few early-stage startups as a tech lead. He obtained his Graduate degree from the Robotics Institute, Carnegie Mellon University, and worked on Autonomous Navigation, Perception and Artificial Intelligence as a Research and Teaching Assistant.
  short_bio: Principal AI Engineering Lead for Autonomous Systems at Microsoft AI + Research
  uri: "https://praveenp.com"
  location: U.S.A
  links:
    - label: "Email"
      icon: "fa fa-2x fa-envelope-square"
      url: "mailto:email@praveenp.com"
    - label: "Website"
      icon: "fa fa-2x fa-link"
      url: "https://praveenp.com"
    - label: "Twitter"
      icon: "fa fa-2x fa-twitter-square"
      url: "https://twitter.com/PraveenPSamy"
    - label: "GitHub"
      icon: "fa fa-2x fa-github"
      url: "https://github.com/praveen-palanisamy"

# comment
disqus:
  name: praveen-palanisamy-github

# analytics
## google analytics
ga:
  # id:

## google optimize
go:
  # id:

## donation
donation: off # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: off # index page carousel switch
blog_carousel: on # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Default front matter content https://jekyllrb.com/docs/configuration/front-matter-defaults/

defaults:
  - scope:
      path: ""  # All files
      type: pages
    values:
      layout: "default"
      author_profile: true
  - scope:
      path: ""  # All files
      type: posts
    values:
      layout: "post"
      author_profile: true